apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-core
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leketech/internal-developer-platform.git
    targetRevision: HEAD
    path: argocd/core
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: argocd-secret
    jsonPointers:
    - /data