apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpc-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leketech/internal-developer-platform.git
    targetRevision: HEAD
    path: terraform/modules/vpc
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /status